name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    services:
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 15672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0
          elixir-version: 1.10.3
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build
          restore-keys: |
            ${{ runner.os }}-test-build
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Vault
        run: sh ./test/support/vault/docker.sh
        env:
          RABBITMQ_URL: http://localhost:${{ job.services.rabbitmq.ports['15672'] }}
      - name: Run Tests
        run: mix test
