name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    services:
      rabbitmq:
        image: rabbitmq
        ports: ['5672:5672']
        env:
          RABBITMQ_USER: guest
          RABBITMQ_PASS: guest
          RABBITMQ_VHOST: "/"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.3
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build
          restore-keys: |
            ${{ runner.os }}-test-build
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Vault
        run: sh test/support/vault/docker.sh
      - name: Run Tests
        run: mix test
